import { Inter } from "next/font/google";
import "../../../app/globals.css";
import SidebarFlowBot from "@/components/sidebarflowbot/sidebarflowbot";
import Navbar from "@/components/navbar/navbarFlowbot";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Peak Mobile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviderWrapper>
          <div className="flex flex-col md:flex-row min-h-screen w-full overflow-hidden">
            <div className="hidden md:block">
              <SidebarFlowBot />
            </div>
            <div className="flex flex-col flex-1 w-full min-w-0 overflow-y-auto">
              <Navbar />
              <main className="flex-1 w-full">
                {children}
              </main>
            </div>
          </div>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}