// src/app/api/apps/[appId]/layout.js
import { Inter } from "next/font/google";
import "../../../app/globals.css";
import SidebarSms from "@/components/sidebarsms/sidebarsms";
import SmsNavbar from "@/components/sms-navbar/smsnavbar";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Peak Mobile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviderWrapper>
          <div>
            <SidebarSms />
            <SmsNavbar />
            {children}
          </div>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
